# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import database as dbd


class Ui_list_client(object):

    def fill_list(self):
        '''заполняет список'''

        mas = dbd.list_off_all_students()
        i = 1
        for person in mas:
            self.Client_info.addItem(str(i) + '. ФИО: ' + person[1]['ФИО'] + '\n' \
                                     + 'Общежитие: ' + str(person[1]['Общежитие']) + '\n' \
                                     + 'Комната: ' + str(person[1]['Комната']) + '\n' \
                                     + 'Пол: ' + person[1]['Пол'] + '\n')
            i = i + 1

    def openClient(self):
        from Client import Ui_Client
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Client()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, list_client):
        list_client.setObjectName("list_client")
        list_client.resize(480, 491)
        list_client.setMinimumSize(QtCore.QSize(300, 300))
        list_client.setMaximumSize(QtCore.QSize(1000, 500))
        self.centralwidget = QtWidgets.QWidget(list_client)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 445, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(17)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_client_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.import_client_btn.setMinimumSize(QtCore.QSize(213, 40))
        self.import_client_btn.setMaximumSize(QtCore.QSize(213, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.import_client_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.import_client_btn.setFont(font)
        self.import_client_btn.setStyleSheet("background-color: rgb(135, 206, 235);")
        self.import_client_btn.setObjectName("import_client_btn")
        self.horizontalLayout.addWidget(self.import_client_btn)



        self.horizontalLayout.addWidget(self.import_client_btn)
        self.back_to_client_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.back_to_client_btn.setMinimumSize(QtCore.QSize(213, 40))
        self.back_to_client_btn.setMaximumSize(QtCore.QSize(213, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 206, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.back_to_client_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_client_btn.setFont(font)
        self.back_to_client_btn.setStyleSheet("background-color: rgb(135, 206, 235);")
        self.back_to_client_btn.setObjectName("back_to_client_btn")

        self.back_to_client_btn.clicked.connect(self.openClient)
        self.back_to_client_btn.clicked.connect(list_client.close)

        self.horizontalLayout.addWidget(self.back_to_client_btn)
        self.Client_info = QtWidgets.QListWidget(self.centralwidget)
        self.Client_info.setGeometry(QtCore.QRect(20, 89, 440, 371))
        self.Client_info.setAutoFillBackground(False)
        self.Client_info.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"selection-color: rgb(85, 170, 255);")
        self.Client_info.setObjectName("Client_info")



        item = QtWidgets.QListWidgetItem()

        item = QtWidgets.QListWidgetItem()

        list_client.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(list_client)
        self.statusbar.setObjectName("statusbar")
        list_client.setStatusBar(self.statusbar)

        self.retranslateUi(list_client)
        QtCore.QMetaObject.connectSlotsByName(list_client)

        self.fill_list()

    def retranslateUi(self, list_client):
        _translate = QtCore.QCoreApplication.translate
        list_client.setWindowTitle(_translate("list_client", "Список клиентов"))
        self.import_client_btn.setText(_translate("list_client", "Импортировать в Excel"))
        self.back_to_client_btn.setText(_translate("list_client", "Вернуться в меню клиента"))
        __sortingEnabled = self.Client_info.isSortingEnabled()
        self.Client_info.setSortingEnabled(False)
        self.Client_info.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    list_client = QtWidgets.QMainWindow()
    ui = Ui_list_client()
    ui.setupUi(list_client)
    list_client.show()
    sys.exit(app.exec_())
